global using System.ComponentModel.DataAnnotations;
global using System.Collections.Generic;
global using System.Linq;
global using System.Text;
global using System.Threading.Tasks;
global using lw.Core.Data;
global using lw.Infra.DataContext;
global using Microsoft.AspNetCore.Http;
global using Microsoft.EntityFrameworkCore;